language: objective-c

osx_image: xcode8

install:
  - cd example
  - mkdir -p /Users/travis/build/engsshi/.nvm
  - export NVM_DIR="/Users/travis/build/engsshi/.nvm"
  - brew install nvm
  - source $(brew --prefix nvm)/nvm.sh
  # TODO npm 2 started stalling on Travis, t11852928
  - nvm install 5
  - rm -Rf "${TMPDIR}/jest_preprocess_cache"
  - wget https://github.com/yarnpkg/yarn/releases/download/v0.16.0/yarn-0.16.0.js
  - export yarn="node $(pwd)/yarn-0.16.0.js"
  - $yarn install
  - npm install

script: npm run travis

